"""
Templates for generating finetuned model YAML configurations.

This module provides functions to auto-generate the YAML config for serving
finetuned models using FinetuneModelConfig (type: finetune).
"""

import logging
from pathlib import Path

logger = logging.getLogger(__name__)


def generate_finetuned_model_yaml(
    lora_adapter_path: str = None,
    base_model_dict: dict = None,
    model_name: str = None,
    output_path: Path = None,
    data_path: str = None,
    queue: str = "gpu_h100",
    charge_group: str = "cellmap",
    json_data: dict = None,
    scale: str = "s0",
    weights_path: str = None,
) -> Path:
    """
    Generate .yaml configuration for serving a finetuned model.

    The generated YAML uses type: finetune, which delegates to
    FinetuneModelConfig. This loads the base model via its own
    ModelConfig, applies the LoRA adapter, and serves the result.

    Args:
        lora_adapter_path: Path to the saved LoRA adapter directory
        weights_path: Instead of an adapter, a full state dict from a
            --lora-r 0 (full finetune) run. Exactly one of the two.
        base_model_dict: Dict describing the base model (from model_config.to_dict())
        model_name: Name of the finetuned model
        output_path: Where to write the .yaml file
        data_path: Path to actual dataset (REQUIRED - no placeholders)
        queue: LSF queue name
        charge_group: LSF charge group
        json_data: Optional dict with input_norm and postprocess from base model
        scale: Scale level (e.g., "s0", "s1") from base model

    Returns:
        Path to the generated YAML file
    """
    import yaml as yaml_lib

    if not data_path or data_path == "/path/to/your/data.zarr":
        raise ValueError(
            "data_path is required and cannot be a placeholder. "
            "Must provide actual dataset path from training corrections."
        )

    # Build the model entry
    if bool(lora_adapter_path) == bool(weights_path):
        raise ValueError("generate_finetuned_model_yaml needs exactly one of lora_adapter_path / weights_path")
    model_entry = {
        "type": "finetune",
        "name": model_name,
        "base_model": base_model_dict,
        "scale": scale,
    }
    if weights_path:
        model_entry["weights_path"] = weights_path
    else:
        model_entry["lora_adapter_path"] = lora_adapter_path

    # Build the full YAML structure
    yaml_dict = {
        "data_path": data_path,
        "charge_group": charge_group,
        "queue": queue,
        "models": [model_entry],
    }

    # Add json_data (normalization/postprocessing)
    if json_data:
        yaml_dict["json_data"] = json_data

    # Header comment
    header = (
        f"# Finetuned model configuration: {model_name}\n"
        f"# Auto-generated by CellMap-Flow finetuning workflow\n"
        f"#\n"
    )
    if not json_data:
        header += (
            "# WARNING: No normalization found in base model!\n"
            "# Model may not work correctly without proper normalization.\n"
            "#\n"
        )

    # Write to file
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    yaml_content = yaml_lib.dump(yaml_dict, default_flow_style=False, sort_keys=False)

    with open(output_path, "w") as f:
        f.write(header)
        f.write(yaml_content)

    logger.info(f"Generated finetuned model YAML: {output_path}")

    return output_path


def generate_current_config_yaml(
    models: list,
    data_path: str,
    queue: str = "gpu_h100",
    charge_group: str = "cellmap",
    walltime: str = None,
    json_data: dict = None,
) -> str:
    """
    Build YAML text snapshotting the dashboard's current live server config
    (whatever models/normalization/postprocessing/queue are active right
    now), so it can be handed back to `cellmap_flow_yaml` later.

    Unlike generate_finetuned_model_yaml (which describes one specific
    finetune job), this is a general "export what's currently running"
    dump -- it doesn't write to disk itself, callers decide where the
    result goes (a download response, a file, etc).

    Args:
        models: list of model entry dicts (each from ModelConfig.to_dict())
        data_path: current dataset path
        queue: LSF queue name
        charge_group: LSF charge group
        walltime: LSF run limit ("HH:MM" or minutes); omitted when unset, so
            the reloaded config falls back to the built-in default
        json_data: dict with "input_norm"/"postprocess" keys reflecting the
            currently active normalization/postprocessing, if any

    Returns:
        YAML text (str) ready to write to a file.
    """
    import yaml as yaml_lib

    yaml_dict = {
        "data_path": data_path,
        "charge_group": charge_group,
        "queue": queue,
    }
    if walltime:
        yaml_dict["walltime"] = walltime

    has_json_data = json_data and (
        json_data.get("input_norm") or json_data.get("postprocess")
    )
    if has_json_data:
        yaml_dict["json_data"] = json_data

    yaml_dict["models"] = models

    header = (
        "# CellMap-Flow exported configuration\n"
        "# Reload with: cellmap_flow_yaml <this file>\n"
        "#\n"
    )
    if not has_json_data:
        header += (
            "# WARNING: no normalization/postprocessing was active when this\n"
            "# was exported -- add a json_data block manually if your model(s)\n"
            "# need one (e.g. logit outputs need a SigmoidPostprocessor).\n"
            "#\n"
        )

    yaml_content = yaml_lib.dump(yaml_dict, default_flow_style=False, sort_keys=False)
    return header + yaml_content
