"""
Templates for generating finetuned model YAML configurations.

This module provides functions to auto-generate the YAML config for serving
finetuned models using FinetuneModelConfig (type: finetune).
"""

import logging
from pathlib import Path

logger = logging.getLogger(__name__)


def generate_finetuned_model_yaml(
    lora_adapter_path: str,
    base_model_dict: dict,
    model_name: str,
    output_path: Path,
    data_path: str,
    queue: str = "gpu_h100",
    charge_group: str = "cellmap",
    json_data: dict = None,
    scale: str = "s0",
) -> Path:
    """
    Generate .yaml configuration for serving a finetuned model.

    The generated YAML uses type: finetune, which delegates to
    FinetuneModelConfig. This loads the base model via its own
    ModelConfig, applies the LoRA adapter, and serves the result.

    Args:
        lora_adapter_path: Path to the saved LoRA adapter directory
        base_model_dict: Dict describing the base model (from model_config.to_dict())
        model_name: Name of the finetuned model
        output_path: Where to write the .yaml file
        data_path: Path to actual dataset (REQUIRED - no placeholders)
        queue: LSF queue name
        charge_group: LSF charge group
        json_data: Optional dict with input_norm and postprocess from base model
        scale: Scale level (e.g., "s0", "s1") from base model

    Returns:
        Path to the generated YAML file
    """
    import yaml as yaml_lib

    if not data_path or data_path == "/path/to/your/data.zarr":
        raise ValueError(
            "data_path is required and cannot be a placeholder. "
            "Must provide actual dataset path from training corrections."
        )

    # Build the model entry
    model_entry = {
        "type": "finetune",
        "name": model_name,
        "lora_adapter_path": lora_adapter_path,
        "base_model": base_model_dict,
        "scale": scale,
    }

    # Build the full YAML structure
    yaml_dict = {
        "data_path": data_path,
        "charge_group": charge_group,
        "queue": queue,
        "models": [model_entry],
    }

    # Add json_data (normalization/postprocessing)
    if json_data:
        yaml_dict["json_data"] = json_data

    # Header comment
    header = (
        f"# Finetuned model configuration: {model_name}\n"
        f"# Auto-generated by CellMap-Flow finetuning workflow\n"
        f"#\n"
    )
    if not json_data:
        header += (
            "# WARNING: No normalization found in base model!\n"
            "# Model may not work correctly without proper normalization.\n"
            "#\n"
        )

    # Write to file
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    yaml_content = yaml_lib.dump(yaml_dict, default_flow_style=False, sort_keys=False)

    with open(output_path, "w") as f:
        f.write(header)
        f.write(yaml_content)

    logger.info(f"Generated finetuned model YAML: {output_path}")

    return output_path
