"""
Templates for generating finetuned model YAML configurations.

This module provides functions to auto-generate the YAML config for serving
finetuned models using FinetuneModelConfig (type: finetune).
"""

import logging
from pathlib import Path

from cellmap_flow.jobs.site import current_site

logger = logging.getLogger(__name__)

# The finetune CLI prints this with the path of each serving YAML it writes,
# just before TRAINING_ITERATION_COMPLETE; the job manager reads the YAML
# from there. Here, rather than in either of them, so both can import it
# without importing the other.
FINETUNED_MODEL_YAML_MARKER = "FINETUNED_MODEL_YAML:"

# Stand-ins for a data path that are not one. The CLI used to fall back to
# the second while this check only knew the first, so YAMLs pointing at
# /path/to/data.zarr were written without complaint.
PLACEHOLDER_DATA_PATHS = frozenset({"/path/to/your/data.zarr", "/path/to/data.zarr"})


def generate_finetuned_model_yaml(
    lora_adapter_path: str = None,
    base_model_dict: dict = None,
    model_name: str = None,
    output_path: Path = None,
    data_path: str = None,
    queue: str = None,
    charge_group: str = None,
    json_data: dict = None,
    scale: str = None,
    weights_path: str = None,
    resample: bool = False,
    input_voxel_size=None,
    output_voxel_size=None,
) -> Path:
    """
    Generate .yaml configuration for serving a finetuned model.

    The generated YAML uses type: finetune, which delegates to
    FinetuneModelConfig. This loads the base model via its own
    ModelConfig, applies the LoRA adapter, and serves the result.

    Args:
        lora_adapter_path: Path to the saved LoRA adapter directory
        weights_path: Instead of an adapter, a full state dict from a
            --lora-r 0 (full finetune) run. Exactly one of the two.
        base_model_dict: Dict describing the base model (from model_config.to_dict())
        model_name: Name of the finetuned model
        output_path: Where to write the .yaml file
        data_path: Path to actual dataset (REQUIRED - no placeholders)
        queue: LSF queue name; None is the site's default queue
        charge_group: LSF charge group; None is the site's default one
        json_data: Optional dict with input_norm and postprocess from base model
        scale: The level of a multiscale ``data_path`` to serve ("s1"), or
            None for none. With none, the server picks the level by the
            model's input voxel size, which is how the trainer read the same
            ``data_path``. This was always "s0", so a model trained on s1 of
            a multiscale group was served s0.
        resample: the model was trained on the raw resampled to its voxel
            size (its volume's ``resample``), so serve it that way too
        input_voxel_size, output_voxel_size: the voxel sizes the finetune was
            trained at, when not the base model's (run_outputs); the served
            model declares them

    Returns:
        Path to the generated YAML file
    """
    import yaml as yaml_lib

    site = current_site()
    queue = site.default_queue if queue is None else queue
    charge_group = site.default_charge_group if charge_group is None else charge_group

    if not data_path or str(data_path) in PLACEHOLDER_DATA_PATHS:
        raise ValueError(
            "data_path is required and cannot be a placeholder. "
            "Must provide actual dataset path from training corrections."
        )

    # Build the model entry
    if bool(lora_adapter_path) == bool(weights_path):
        raise ValueError("generate_finetuned_model_yaml needs exactly one of lora_adapter_path / weights_path")
    model_entry = {
        "type": "finetune",
        "name": model_name,
        "base_model": base_model_dict,
    }
    if scale:
        model_entry["scale"] = scale
    if input_voxel_size is not None:
        model_entry["input_voxel_size"] = list(input_voxel_size)
    if output_voxel_size is not None:
        model_entry["output_voxel_size"] = list(output_voxel_size)
    if weights_path:
        model_entry["weights_path"] = weights_path
    else:
        model_entry["lora_adapter_path"] = lora_adapter_path

    # Build the full YAML structure
    yaml_dict = {
        "data_path": data_path,
        "charge_group": charge_group,
        "queue": queue,
        "models": [model_entry],
    }
    if resample:
        yaml_dict["resample"] = True

    # Add json_data (normalization/postprocessing)
    if json_data:
        yaml_dict["json_data"] = json_data

    # Header comment
    header = (
        f"# Finetuned model configuration: {model_name}\n"
        f"# Auto-generated by CellMap-Flow finetuning workflow\n"
        f"#\n"
    )
    if not json_data:
        header += (
            "# WARNING: No normalization found in base model!\n"
            "# Model may not work correctly without proper normalization.\n"
            "#\n"
        )

    # Write to file
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    yaml_content = yaml_lib.dump(yaml_dict, default_flow_style=False, sort_keys=False)

    with open(output_path, "w") as f:
        f.write(header)
        f.write(yaml_content)

    logger.info(f"Generated finetuned model YAML: {output_path}")

    return output_path


def generate_current_config_yaml(
    models: list,
    data_path: str,
    queue: str = None,
    charge_group: str = None,
    walltime: str = None,
    json_data: dict = None,
    resample: bool = False,
) -> str:
    """
    Build YAML text snapshotting the dashboard's current live server config
    (whatever models/normalization/postprocessing/queue are active right
    now), so it can be handed back to `cellmap_flow yaml` later.

    Unlike generate_finetuned_model_yaml (which describes one specific
    finetune job), this is a general "export what's currently running"
    dump -- it doesn't write to disk itself, callers decide where the
    result goes (a download response, a file, etc).

    Args:
        models: list of model entry dicts (each from ModelConfig.to_dict())
        data_path: current dataset path
        queue: LSF queue name; None is the site's default queue
        charge_group: LSF charge group; None is the site's default one
        walltime: LSF run limit ("HH:MM" or minutes); omitted when unset, so
            the reloaded config falls back to the built-in default
        json_data: dict with "input_norm"/"postprocess" keys reflecting the
            currently active normalization/postprocessing, if any
        resample: the dashboard's Resample setting; written only when on

    Returns:
        YAML text (str) ready to write to a file.
    """
    import yaml as yaml_lib

    site = current_site()
    queue = site.default_queue if queue is None else queue
    charge_group = site.default_charge_group if charge_group is None else charge_group

    yaml_dict = {
        "data_path": data_path,
        "charge_group": charge_group,
        "queue": queue,
    }
    if walltime:
        yaml_dict["walltime"] = walltime
    if resample:
        yaml_dict["resample"] = True

    has_json_data = json_data and (
        json_data.get("input_norm") or json_data.get("postprocess")
    )
    if has_json_data:
        yaml_dict["json_data"] = json_data

    yaml_dict["models"] = models

    header = (
        "# CellMap-Flow exported configuration\n"
        "# Reload with: cellmap_flow yaml <this file>\n"
        "#\n"
    )
    if not has_json_data:
        header += (
            "# WARNING: no normalization/postprocessing was active when this\n"
            "# was exported -- add a json_data block manually if your model(s)\n"
            "# need one (e.g. logit outputs need a SigmoidPostprocessor).\n"
            "#\n"
        )

    yaml_content = yaml_lib.dump(yaml_dict, default_flow_style=False, sort_keys=False)
    return header + yaml_content
